# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('subject', models.CharField(max_length=500)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('B', 'Email Body'), ('R', 'Recipient email address'), ('S', 'Sender email address'), ('U', 'From URL')], max_length=1)),
                ('emails', models.ManyToManyField(to='email_analysis.Email')),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('emails', models.ManyToManyField(to='email_analysis.Email')),
                ('hosts', models.ManyToManyField(to='email_analysis.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
                ('url_query_string', models.CharField(blank=True, max_length=2000, null=True)),
                ('url_path', models.CharField(default='/', max_length=500)),
                ('url_file', models.CharField(blank=True, max_length=255, null=True)),
                ('emails', models.ManyToManyField(to='email_analysis.Email')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_analysis.Host')),
            ],
        ),
    ]
